package com.dianping.phoenix.lb.deploy.dao;

import com.dianping.phoenix.lb.deploy.model.DeploymentDetail;
import com.dianping.phoenix.lb.deploy.model.DeploymentDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DeploymentDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_detail
     *
     * @mbggenerated
     */
    int countByExample(DeploymentDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_detail
     *
     * @mbggenerated
     */
    int deleteByExample(DeploymentDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_detail
     *
     * @mbggenerated
     */
    int insert(DeploymentDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_detail
     *
     * @mbggenerated
     */
    int insertSelective(DeploymentDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_detail
     *
     * @mbggenerated
     */
    List<DeploymentDetail> selectByExampleWithBLOBsWithRowbounds(DeploymentDetailExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_detail
     *
     * @mbggenerated
     */
    List<DeploymentDetail> selectByExampleWithBLOBs(DeploymentDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_detail
     *
     * @mbggenerated
     */
    List<DeploymentDetail> selectByExampleWithRowbounds(DeploymentDetailExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_detail
     *
     * @mbggenerated
     */
    List<DeploymentDetail> selectByExample(DeploymentDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_detail
     *
     * @mbggenerated
     */
    DeploymentDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DeploymentDetail record, @Param("example") DeploymentDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_detail
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") DeploymentDetail record, @Param("example") DeploymentDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DeploymentDetail record, @Param("example") DeploymentDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeploymentDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(DeploymentDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeploymentDetail record);
}