package com.dianping.phoenix.lb.deploy.dao;

import com.dianping.phoenix.lb.deploy.model.DeploymentTask;
import com.dianping.phoenix.lb.deploy.model.DeploymentTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DeploymentTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_task
     *
     * @mbggenerated
     */
    int countByExample(DeploymentTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_task
     *
     * @mbggenerated
     */
    int deleteByExample(DeploymentTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_task
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_task
     *
     * @mbggenerated
     */
    int insert(DeploymentTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_task
     *
     * @mbggenerated
     */
    int insertSelective(DeploymentTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_task
     *
     * @mbggenerated
     */
    List<DeploymentTask> selectByExampleWithRowbounds(DeploymentTaskExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_task
     *
     * @mbggenerated
     */
    List<DeploymentTask> selectByExample(DeploymentTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_task
     *
     * @mbggenerated
     */
    DeploymentTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_task
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DeploymentTask record, @Param("example") DeploymentTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_task
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DeploymentTask record, @Param("example") DeploymentTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeploymentTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deployment_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeploymentTask record);
}