package com.dianping.phoenix.lb.deploy.model;

import java.io.Serializable;
import java.util.Date;

public class DeploymentTask implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deployment_task.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deployment_task.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deployment_task.strategy
     *
     * @mbggenerated
     */
    private String strategy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deployment_task.error_policy
     *
     * @mbggenerated
     */
    private Integer errorPolicy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deployment_task.auto_continue
     *
     * @mbggenerated
     */
    private Integer autoContinue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deployment_task.deploy_interval
     *
     * @mbggenerated
     */
    private Integer deployInterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deployment_task.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deployment_task.deployed_by
     *
     * @mbggenerated
     */
    private String deployedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deployment_task.begin_date
     *
     * @mbggenerated
     */
    private Date beginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deployment_task.end_date
     *
     * @mbggenerated
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deployment_task.creation_date
     *
     * @mbggenerated
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deployment_task.last_modified_date
     *
     * @mbggenerated
     */
    private Date lastModifiedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deployment_task
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deployment_task.id
     *
     * @return the value of deployment_task.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deployment_task.id
     *
     * @param id the value for deployment_task.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deployment_task.name
     *
     * @return the value of deployment_task.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deployment_task.name
     *
     * @param name the value for deployment_task.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deployment_task.strategy
     *
     * @return the value of deployment_task.strategy
     *
     * @mbggenerated
     */
    public String getStrategy() {
        return strategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deployment_task.strategy
     *
     * @param strategy the value for deployment_task.strategy
     *
     * @mbggenerated
     */
    public void setStrategy(String strategy) {
        this.strategy = strategy == null ? null : strategy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deployment_task.error_policy
     *
     * @return the value of deployment_task.error_policy
     *
     * @mbggenerated
     */
    public Integer getErrorPolicy() {
        return errorPolicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deployment_task.error_policy
     *
     * @param errorPolicy the value for deployment_task.error_policy
     *
     * @mbggenerated
     */
    public void setErrorPolicy(Integer errorPolicy) {
        this.errorPolicy = errorPolicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deployment_task.auto_continue
     *
     * @return the value of deployment_task.auto_continue
     *
     * @mbggenerated
     */
    public Integer getAutoContinue() {
        return autoContinue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deployment_task.auto_continue
     *
     * @param autoContinue the value for deployment_task.auto_continue
     *
     * @mbggenerated
     */
    public void setAutoContinue(Integer autoContinue) {
        this.autoContinue = autoContinue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deployment_task.deploy_interval
     *
     * @return the value of deployment_task.deploy_interval
     *
     * @mbggenerated
     */
    public Integer getDeployInterval() {
        return deployInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deployment_task.deploy_interval
     *
     * @param deployInterval the value for deployment_task.deploy_interval
     *
     * @mbggenerated
     */
    public void setDeployInterval(Integer deployInterval) {
        this.deployInterval = deployInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deployment_task.status
     *
     * @return the value of deployment_task.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deployment_task.status
     *
     * @param status the value for deployment_task.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deployment_task.deployed_by
     *
     * @return the value of deployment_task.deployed_by
     *
     * @mbggenerated
     */
    public String getDeployedBy() {
        return deployedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deployment_task.deployed_by
     *
     * @param deployedBy the value for deployment_task.deployed_by
     *
     * @mbggenerated
     */
    public void setDeployedBy(String deployedBy) {
        this.deployedBy = deployedBy == null ? null : deployedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deployment_task.begin_date
     *
     * @return the value of deployment_task.begin_date
     *
     * @mbggenerated
     */
    public Date getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deployment_task.begin_date
     *
     * @param beginDate the value for deployment_task.begin_date
     *
     * @mbggenerated
     */
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deployment_task.end_date
     *
     * @return the value of deployment_task.end_date
     *
     * @mbggenerated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deployment_task.end_date
     *
     * @param endDate the value for deployment_task.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deployment_task.creation_date
     *
     * @return the value of deployment_task.creation_date
     *
     * @mbggenerated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deployment_task.creation_date
     *
     * @param creationDate the value for deployment_task.creation_date
     *
     * @mbggenerated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deployment_task.last_modified_date
     *
     * @return the value of deployment_task.last_modified_date
     *
     * @mbggenerated
     */
    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deployment_task.last_modified_date
     *
     * @param lastModifiedDate the value for deployment_task.last_modified_date
     *
     * @mbggenerated
     */
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
}